const eresources = {
  hasLoaded: true,
  isPending: false,
  failed: false,
  records: [
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}',
    '{class: "org.olf.kb.TitleInstance", c…}'
  ],
  successfulMutations: [],
  failedMutations: [],
  pendingMutations: [],
  loadedAt: 'Wed Dec 01 2021 07:01:25 GMT+0000 (Greenwich Mean Time)',
  url: 'https://folio-snapshot-okapi.dev.folio.org/erm/resource/electronic?perPage=100&sort=name%3Basc&stats=true',
  headers: 'Headers(undefined) {"content-type" => "application/json;charset=UTF-8"}',
  httpStatus: 200,
  other: {
    pageSize: 100,
    page: 1,
    totalPages: 373,
    meta: '{}',
    totalRecords: 37260,
    total: 37260
  },
  resource: 'eresources',
  module: '@folio/agreements',
  throwErrors: true
};

export default eresources;
