const initialState = {
  discovery: {
    modules: {
      'edge-ncip-1.5.0-SNAPSHOT.12':'Edge NCIP',
      'edge-oai-pmh-2.3.0-SNAPSHOT.54':'OAI-PMH Edge API',
      'edge-orders-2.3.0-SNAPSHOT.39':'Acquisitions - Orders Edge API',
      'edge-patron-4.3.0-SNAPSHOT.53':'Patron Services Edge API',
      'edge-rtac-2.1.0-SNAPSHOT.61':'Real Time Availability Check Edge API',
      'folio_acquisition-units-2.1.100071':'Acquisition units',
      'folio_agreements-5.0.1000505':'ERM agreement functionality for Stripes',
      'folio_agreements-5.0.1000506':'ERM agreement functionality for Stripes',
      'folio_calendar-4.0.100075':'Opening hours',
      'folio_checkin-3.0.1000291':'Item Check-in',
      'folio_checkout-4.0.1000451':'Item Check-out',
      'folio_checkout-4.0.1000452':'Item Check-out',
      'folio_circulation-3.0.1000550':'Circulation manager',
      'folio_circulation-log-1.0.100010':'Description for circulation logs',
      'folio_courses-2.0.1000289':'Maintain courses and reserve items for them',
      'folio_data-export-2.0.1000144':'Data export manager',
      'folio_data-export-2.0.1000145':'Data export manager',
      'folio_data-import-3.0.1000597':'Data Import manager',
      'folio_data-import-3.0.1000598':'Data Import manager',
      'folio_data-import-3.0.1000599':'Data Import manager',
      'folio_developer-3.1.1000140':'Developer settings',
      'folio_eholdings-4.0.1000781':'FOLIO UI module for eHoldings',
      'folio_eholdings-4.0.1000782':'FOLIO UI module for eHoldings',
      'folio_erm-comparisons-1.1.100039':'ERM app for comparison of Agreement and Package objects',
      'folio_erm-usage-4.0.1000210':'eUsage Module',
      'folio_finance-2.1.2000367':'Description for ui-finance',
      'folio_inventory-5.0.10001002':'Inventory manager',
      'folio_invoice-2.1.3000334':'Invoice',
      'folio_invoice-2.1.3000335':'Invoice',
      'folio_invoice-2.1.3000336':'Invoice',
      'folio_licenses-5.0.1000320':'ERM License functionality for Stripes',
      'folio_local-kb-admin-3.0.1000118':'ERM KB Administration for FOLIO with Stripes',
      'folio_marccat-3.0.1000397':'FOLIO UI module for Cataloging',
      'folio_myprofile-3.0.100096':'My profile',
      'folio_notes-3.0.100063':'Note types manager',
      'folio_oai-pmh-1.3.100058':'OAI-PMH manager',
      'folio_orders-2.1.1000862':'Description for orders',
      'folio_orders-2.1.1000863':'Description for orders',
      'folio_organizations-2.1.2000281':'Organizations',
      'folio_organizations-2.1.2000282':'Organizations',
      'folio_organizations-2.1.2000283':'Organizations',
      'folio_plugin-create-inventory-records-1.0.100020':'Create inventory records for Stripes',
      'folio_plugin-create-item-2.1.100053':'Instance-create-item for Stripes',
      'folio_plugin-find-agreement-5.0.100070':'ERM-agreement-finder for Stripes',
      'folio_plugin-find-contact-2.1.100061':'Find and select contacts plugin for Stripes',
      'folio_plugin-find-eresource-1.0.100015':'ERM-eresource-finder for Stripes',
      'folio_plugin-find-erm-usage-data-provider-2.0.100031':'ERM-Usage-data-provider-finder for Stripes',
      'folio_plugin-find-import-profile-3.0.100053':'Find and select Data Import Profiles plugin for Stripes',
      'folio_plugin-find-instance-4.0.100053':'Instance-finder for Stripes',
      'folio_plugin-find-interface-2.1.100054':'Find and select interfaces plugin for Stripes',
      'folio_plugin-find-license-5.0.100072':'License-finder for Stripes',
      'folio_plugin-find-organization-2.1.100055':'Organization-finder for Stripes',
      'folio_plugin-find-package-title-1.0.100017':'Stripes plugin to find packages and titles',
      'folio_plugin-find-po-line-2.1.100064':'Find and select PO lines plugin for Stripes',
      'folio_plugin-find-user-4.0.1000119':'User-finder for Stripes',
      'folio_quick-marc-1.1.100086':'Quick MARC editor',
      'folio_receiving-1.1.1000172':'Description for receiving',
      'folio_requests-4.0.1000545':'Requests manager',
      'folio_search-3.0.1000193':'Search across the Codex',
      'folio_servicepoints-3.0.100072':'Service Points handler for Stripes',
      'folio_stripes-core-6.0.1000758':'The starting point for Stripes applications',
      'folio_stripes-erm-components-4.0.1000177':'Component library for Stripes ERM applications',
      'folio_stripes-smart-components-5.0.1000823':'Connected Stripes components',
      'folio_tags-3.0.100058':'Tags manager',
      'folio_tenant-settings-4.0.1000132':'Tenant settings',
      'folio_users-5.0.10001213':'User management',
      'folio_users-5.0.10001214':'User management',
      'folio_users-5.0.10001215':'User management',
      'folio_users-5.0.10001216':'User management',
      'mod-agreements-3.0.0-SNAPSHOT.298':'mod-agreements',
      'mod-authtoken-2.6.0-SNAPSHOT.73':'authtoken',
      'mod-calendar-1.10.0-SNAPSHOT.115':'Calendar module',
      'mod-circulation-19.1.0-SNAPSHOT.650':'Circulation Module',
      'mod-circulation-storage-12.1.0-SNAPSHOT.256':'Circulation Storage Module',
      'mod-codex-ekb-1.6.1-SNAPSHOT.103':'EBSCO Knowledge Base Codex',
      'mod-codex-inventory-1.8.0-SNAPSHOT.80':'Codex wrapper for Inventory',
      'mod-codex-mux-2.8.1-SNAPSHOT.94':'Codex Multiplexer',
      'mod-configuration-5.5.0-SNAPSHOT.80':'Configuration',
      'mod-courses-1.0.6-SNAPSHOT.96':'Courses Storage Module',
      'mod-data-export-2.2.0-SNAPSHOT.151':'Data Export Module',
      'mod-data-import-1.11.0-SNAPSHOT.142':'Data Import Module',
      'mod-data-import-converter-storage-1.9.0-SNAPSHOT.118':'Data Import Converter Storage',
      'mod-email-1.9.0-SNAPSHOT.45':'email',
      'mod-erm-usage-2.11.0-SNAPSHOT.111':'erm-usage',
      'mod-erm-usage-harvester-1.9.0-SNAPSHOT.79':'erm-usage-harvester',
      'mod-event-config-1.6.0-SNAPSHOT.40':'mod-event-config',
      'mod-feesfines-15.9.0-SNAPSHOT.91':'feesfines',
      'mod-finance-3.1.0-SNAPSHOT.101':'Finance business logic module',
      'mod-finance-storage-5.1.0-SNAPSHOT.118':'Finance CRUD module',
      'mod-gobi-2.0.0-SNAPSHOT.114':'GOBI® Module',
      'mod-graphql-1.2.1000236':'GraphQL API for FOLIO',
      'mod-inventory-16.1.0-SNAPSHOT.287':'Inventory Module',
      'mod-inventory-storage-19.4.0-SNAPSHOT.463':'Inventory Storage Module',
      'mod-invoice-4.1.0-SNAPSHOT.158':'Invoice business logic module',
      'mod-invoice-storage-4.1.0-SNAPSHOT.74':'Invoice CRUD module',
      'mod-kb-ebsco-java-3.5.3-SNAPSHOT.244':'kb-ebsco',
      'mod-licenses-3.0.0-SNAPSHOT.146':'mod-licenses',
      'mod-login-7.1.0-SNAPSHOT.84':'login',
      'mod-login-saml-2.1.0-SNAPSHOT.56':'SAML login',
      'mod-marccat-2.3.0-SNAPSHOT.385':'MARCcat',
      'mod-ncip-1.5.0-SNAPSHOT.23':'NCIP',
      'mod-notes-2.9.1-SNAPSHOT.156':'Notes',
      'mod-notify-2.7.0-SNAPSHOT.96':'Notify',
      'mod-oai-pmh-3.2.0-SNAPSHOT.132':'OAI-PMH Repository Module',
      'mod-orders-11.1.0-SNAPSHOT.343':'Orders Business Logic Module',
      'mod-orders-storage-11.1.0-SNAPSHOT.187':'Orders CRUD module',
      'mod-organizations-1.1.0-SNAPSHOT.15':'Organizations business logic module',
      'mod-organizations-storage-3.2.0-SNAPSHOT.51':'Organizations CRUD module',
      'mod-password-validator-1.8.0-SNAPSHOT.20':'Password Validator Module',
      'mod-patron-4.3.0-SNAPSHOT.57':'Patron Services Module',
      'mod-patron-blocks-1.1.0-SNAPSHOT.28':'Patron Blocks Module',
      'mod-permissions-5.12.0-SNAPSHOT.88':'permissions',
      'mod-pubsub-1.3.0-SNAPSHOT.97':'Pubsub',
      'mod-quick-marc-1.2.0-SNAPSHOT.60':'quickMARC',
      'mod-rtac-1.6.0-SNAPSHOT.50':'Real Time Availability Check Module',
      'mod-sender-1.4.0-SNAPSHOT.24':'Mod sender',
      'mod-source-record-manager-2.4.0-SNAPSHOT.306':'Source Record Manager Module',
      'mod-source-record-storage-4.1.0-SNAPSHOT.189':'Source Record Storage Module',
      'mod-tags-0.6.1-SNAPSHOT.47':'Tags',
      'mod-template-engine-1.10.0-SNAPSHOT.61':'Template engine module',
      'mod-user-import-3.3.0-SNAPSHOT.46':'User import',
      'mod-users-17.1.1-SNAPSHOT.141':'users',
      'mod-users-bl-6.1.0-SNAPSHOT.92':'users business logic',
      'okapi-3.1.2':'Okapi'
    },
    interfaces: {
      'erm':'3.0',
      '_tenant':'1.2',
      'codex':'3.3',
      'authtoken':'2.0',
      'calendar':'4.0',
      'requests-reports':'0.7',
      'inventory-reports':'0.4',
      'pick-slips':'0.2',
      'request-move':'0.7',
      'loan-anonymization':'0.1',
      'declare-item-lost':'0.2',
      'change-due-date':'0.1',
      'claim-item-returned':'0.2',
      'circulation':'9.4',
      'circulation-rules':'1.1',
      'patron-action-session':'0.2',
      '_timer':'1.0',
      'circulation-event-handlers':'0.1',
      'request-storage-batch':'0.3',
      'loan-storage':'7.1',
      'anonymize-storage-loans':'0.1',
      'circulation-rules-storage':'1.0',
      'loan-policy-storage':'2.1',
      'request-storage':'3.3',
      'fixed-due-date-schedules-storage':'2.0',
      'staff-slips-storage':'1.0',
      'cancellation-reason-storage':'1.1',
      'patron-notice-policy-storage':'0.12',
      'request-policy-storage':'1.0',
      'request-preference-storage':'2.0',
      'scheduled-notice-storage':'0.4',
      'patron-action-session-storage':'0.2',
      'check-in-storage':'0.2',
      'codex-packages':'1.0',
      '_jsonSchemas':'1.0',
      '_ramls':'1.0',
      'configuration':'2.0',
      'course-reserves-storage':'0.3',
      'term-storage':'0.1',
      'department-storage':'0.1',
      'course-type-storage':'0.1',
      'processing-status-storage':'0.1',
      'copyright-status-storage':'0.1',
      'role-storage':'0.1',
      'course-storage':'0.1',
      'reserves-storage':'0.1',
      'data-export':'3.0',
      'data-import':'3.0',
      'data-import-converter-storage':'1.2',
      'converter-storage-forms-configs':'1.0',
      'field-protection-settings':'1.0',
      'email':'1.1',
      'delayedTasks':'2.0',
      'usage-data-providers':'2.5',
      'aggregator-settings':'1.2',
      'counter-reports':'1.6',
      'custom-reports':'1.0',
      'erm-usage/files':'1.0',
      'erm-usage-harvester':'1.2',
      '_start':'1.0',
      'mod-event':'1.0',
      'feesfines':'15.3',
      'finance.budgets':'1.2',
      'finance.fund-types':'1.1',
      'finance.funds':'1.3',
      'finance.fiscal-years':'1.1',
      'finance.group-fund-fiscal-years':'1.1',
      'finance.ledgers':'1.5',
      'finance.groups':'1.1',
      'finance.transactions':'4.0',
      'finance.order-transaction-summaries':'1.2',
      'finance.group-fiscal-year-summaries':'1.2',
      'finance.invoice-transaction-summaries':'2.0',
      'finance.exchange-rate':'1.0',
      'finance.expense-classes':'1.0',
      'finance-storage.budgets':'2.1',
      'finance-storage.expense-classes':'1.0',
      'finance-storage.budget-expense-classes':'1.0',
      'finance-storage.fiscal-years':'2.1',
      'finance-storage.fund-types':'1.0',
      'finance-storage.funds':'3.0',
      'finance-storage.groups':'1.1',
      'finance-storage.ledgers':'2.3',
      'finance-storage.transactions':'3.0',
      'finance-storage.order-transaction-summaries':'1.1',
      'finance-storage.invoice-transaction-summaries':'2.0',
      'gobi':'1.9',
      'graphql':'0.0.0',
      'inventory':'10.6',
      'inventory-batch':'0.5',
      'inventory-config':'0.1',
      'isbn-utils':'2.0',
      'inventory-move':'0.2',
      'inventory-event-handlers':'0.1',
      'item-storage':'8.5',
      'item-storage-batch-sync':'0.5',
      'holdings-storage':'4.3',
      'holdings-storage-batch-sync':'0.3',
      'instance-storage':'7.4',
      'instance-preceding-succeeding-titles':'0.1',
      'instance-storage-batch':'0.3',
      'instance-storage-batch-sync':'0.3',
      'loan-types':'2.2',
      'material-types':'2.2',
      'shelf-locations':'1.1',
      'location-units':'2.0',
      'locations':'3.0',
      'instance-relationship-types':'1.0',
      'identifier-types':'1.2',
      'contributor-types':'2.0',
      'contributor-name-types':'1.2',
      'inventory-record-bulk':'1.0',
      'instance-formats':'2.0',
      'instance-types':'2.0',
      'nature-of-content-terms':'1.0',
      'classification-types':'1.2',
      'alternative-title-types':'1.0',
      'modes-of-issuance':'1.1',
      'instance-statuses':'1.0',
      'electronic-access-relationships':'1.0',
      'statistical-code-types':'1.0',
      'statistical-codes':'1.0',
      'ill-policies':'1.0',
      'holdings-types':'1.0',
      'call-number-types':'1.0',
      'instance-note-types':'1.0',
      'holdings-note-types':'1.0',
      'item-note-types':'1.0',
      'item-damaged-statuses':'1.0',
      'service-points':'3.2',
      'service-points-users':'1.0',
      'hrid-settings-storage':'1.1',
      'oaipmhview':'1.1',
      'invoice':'5.5',
      'voucher':'2.2',
      'voucher-number':'1.0',
      'batch-voucher.export-configurations':'1.1',
      'batch-group':'1.1',
      'batch-voucher.batch-vouchers':'2.0',
      'batch-voucher.batch-voucher-exports':'1.1',
      'invoice-storage.invoices':'4.1',
      'invoice-storage.invoice-lines':'3.1',
      'invoice-storage.invoice-number':'1.0',
      'invoice-storage.invoice-line-number':'1.0',
      'voucher-storage.vouchers':'1.2',
      'voucher-storage.voucher-lines':'2.1',
      'voucher-storage.voucher-number':'1.0',
      'batch-voucher-storage.export-configurations':'1.0',
      'batch-voucher-storage.batch-vouchers':'2.0',
      'batch-voucher-storage.batch-voucher-exports':'1.1',
      'batch-group-storage.batch-groups':'1.0',
      'eholdings':'2.1',
      'licenses':'3.0',
      'login':'7.0',
      'login-saml':'2.0',
      'marccat':'2.0',
      'ncip':'1.0',
      'notes':'1.0',
      'notify':'2.1',
      'patron-notice':'1.1',
      'oai-pmh':'3.0',
      'orders':'10.5',
      'order-lines':'1.5',
      'po-number':'1.0',
      'receiving':'1.1',
      'pieces':'2.0',
      'order-templates':'1.0',
      'acquisitions-units':'1.1',
      'titles':'1.2',
      'configuration.reasons-for-closure':'1.0',
      'configuration.prefixes':'1.1',
      'configuration.suffixes':'1.1',
      'orders-storage.alerts':'3.0',
      'orders-storage.pieces':'4.0',
      'orders-storage.titles':'1.1',
      'orders-storage.po-lines':'9.3',
      'orders-storage.purchase-orders':'7.1',
      'orders-storage.receiving-history':'3.2',
      'orders-storage.reporting-codes':'3.0',
      'orders-storage.po-number':'2.0',
      'orders-storage.po-line-number':'1.0',
      'orders-storage.order-invoice-relationships':'1.0',
      'orders-storage.order-templates':'1.0',
      'acquisitions-units-storage.units':'1.1',
      'acquisitions-units-storage.memberships':'1.0',
      'orders-storage.configuration.reasons-for-closure':'1.0',
      'orders-storage.configuration.prefixes':'1.0',
      'orders-storage.configuration.suffixes':'1.0',
      'organizations.organizations':'1.0',
      'organizations-storage.addresses':'1.1',
      'organizations-storage.categories':'1.1',
      'organizations-storage.contacts':'2.0',
      'organizations-storage.emails':'1.1',
      'organizations-storage.interfaces':'2.1',
      'organizations-storage.phone-numbers':'2.0',
      'organizations-storage.urls':'1.1',
      'organizations-storage.organizations':'3.1',
      'password-validator':'1.0',
      'patron':'4.1',
      'automated-patron-blocks':'0.1',
      'user-summary':'0.1',
      'patron-blocks-event-handlers':'1.0',
      'patron-block-conditions':'0.1',
      'patron-block-limits':'0.1',
      'permissions':'5.3',
      '_tenantPermissions':'1.1',
      'pubsub-event-types':'0.1',
      'pubsub-publishers':'0.1',
      'pubsub-subscribers':'0.1',
      'pubsub-audit':'0.1',
      'pubsub-publish':'0.1',
      'records-editor.records':'1.1',
      'rtac':'1.4',
      'message-delivery':'1.0',
      'source-manager-job-executions':'1.0',
      'source-manager-records':'1.0',
      'source-manager-parsed-records':'1.0',
      'mapping-rules-provider':'1.0',
      'source-manager-event-handlers':'0.1',
      'source-storage-snapshots':'2.0',
      'source-storage-records':'2.0',
      'source-storage-source-records':'2.0',
      'source-storage-test-records':'2.0',
      'source-storage-batch':'0.1',
      'source-storage-event-handlers':'0.1',
      'tags':'1.0',
      'template-engine':'2.2',
      'user-import':'2.1',
      'users':'15.2',
      'custom-fields':'2.0',
      'users-bl':'6.0',
      'okapi-proxy':'1.9',
      'okapi':'1.9'
    }
  }
};

export default initialState;
